### ISSUE TITLE
Trollbloods warbeast point cost are 0

### ISSUE THREAD

**Issue by HippySi** [BSData/warmahordes#29]
Just started using this but most of the Trollblood warbeasts have a point cost of 0. The rest seems OK but only had a quick glance.

**Comment by Obiken** [comment]
Interesting, looks like I put in the warbeasts in one go where I somehow thought Troll warbeasts should be free. Strange.

I'll correct it shortly.

**Comment by Obiken** [comment]
Corrected error. Will release it now.
