### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by nolanjurgens** [BSData/warmahordes#30]
I would like to have admin/dev access to the Warmahordes repo so that I can help add content and be a second set of eyes for factions I have access to.

**Comment by amis92** [comment]
Great, we need you! :) Please accept the invitation. Hopefully you know how we work here, seeing as you have some previous activity on GitHub. Cheers!

PS Just to be sure: https://github.com/BSData/bsdata/wiki/Developer-Guide

**Comment by amis92** [comment]
Okay, just now noticed you were already in organisation before. Ignore then all the rant. Access granted (no accept required as you were member previously).
