### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by JimOrtiz** [BSData/warmahordes#31]
I'd like to work on adding the Cygnar catalog to the repository.  I made a fork, added a Cygnar catalog, and started working through the first Warcaster in the book, using Khador as a basis. I noticed that a few of the shared rules have shared GUIDs between Khador and Protectorate.  Is there an easy way to copy those from catalog to catalog?

**Comment by Obiken** [comment]
Welcome aboard, the join request will probably go through as soon as an admin sees it.

What I've done to to form the basis of a new catalog is basically to copy all rules and shared entries in a text editor from another catalog. And then run a home made program to get mercenary entries over.

If you put up yours I can do bit on it.

**Comment by amis92** [comment]
@JimOrtiz - Invitation sent, please accept to join the warmahordes team :)
