### ISSUE TITLE
question - Is anyone against me making a major change to khador warcasters?

### ISSUE THREAD

**Issue by robbert229** [BSData/warmahordes#36]
I was thinking about replacing the multiple named warcasters with a single warcaster with an option for the different versions. As of right now you can have different sorchas as long as they aren't the same.

**Comment by JimOrtiz** [comment]
I've been using conditional "Max in Roster" modifiers in the Cygnar catalog.  Essentially setting max in roster for Stryker1 to 0 if Stryker2 or Stryker3 is in the roster, etc. for each version.  The list provides a validation warning if two versions are selected at the same time.  It does mean any old versions need to be modified when a new version is added.

Thinking about it some more, we could add a shared entry to each version that's max in roster 1 instead:
Kommander Sorscha Kratikoff
   |_ Link to: Sorscha Kratikoff

The validation error would be something like "Roster limit exceeded on Sorsha Kratikoff, max in roster: 1".

The nice thing about the modifiers or shared entries is that they'd work when PP creates Epic Warcaster versions of the Character Junior Warcasters.  You can't change a category in a sub-selection that way.

I do feel like it'd be better if the rule was applied to all the catalogs the same way.  I think my vote is for a shared "Character Name" entry.  It'd be relatively quick to apply to all the existing catalogs, and is more maintainable than my current  modifier approach.

**Comment by nberndt** [comment]
So have a character entry and then their different versions from there? Kind of like this:

Sorscha Kratikoff
-Kommander Sorscha
-Forward Kommander Sorscha

If so I think this would work nicely.

**Comment by JimOrtiz** [comment]
I was thinking the opposite of that:
Kommander Sorscha

**Comment by Obiken** [comment]
I like the suggestion. I'd say go ahead, and then we can test how it works.
