### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by nberndt** [BSData/warmahordes#37]
Hey, I play Khador in warmachine and I want to help improve stuff. The changed made so far by Robbert229 were made by me but he submitted them because I did not know how to use GitHub at the  time. I want to help even more, so he is teaching me how to do this all on my own.

**Comment by JimOrtiz** [comment]
Welcome!  This might have to be titled [Join Request] to trigger a response.  Tagging @amis92 since they invited the last few join requests.

**Comment by amis92** [comment]
Yup, I'm currently the only active owner.

@nberndt - please don't forget to accept your invitation, and welcome aboard!
