### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by nberndt** [BSData/warmahordes#39]
This is nberndt again.I made a join request just the other day. However, I realized the email on my account had a typo in it so I never got an invitation email. Sorry for the inconvenience.

**Comment by JimOrtiz** [comment]
Hmm, I can't remember (it's only been about a month, you'd think I could), is accepting the join request something you can do via the GitHub site without having to use something from the email?  I wonder if @amis92 thought this was a response in the original closed thread and missed it.

**Comment by amis92** [comment]
No response I noticed.

There is no problem in accepting the invitation without email (though I encourage you to fix the typo! :)

Just go log in and open our organization's homepage. It waits for you there: https://github.com/BSData

**Comment by nberndt** [comment]
I just joined! Thanks for the help.
