### ISSUE TITLE
Question: Battlegroup allocation for Warjacks/Warbeasts

### ISSUE THREAD

**Issue by JimOrtiz** [BSData/warmahordes#42]
I've been thinking some more about themes and some of them treat warjacks in the caster's battlegroup differently than those that are Marshalled or are in a Junior Warcaster's battlegroup.

A couple examples: 
The tier 1 benefit for Nemo1's "Eye of the Storm" theme is:
    Journeyman Warcasters and warjacks they control gain Advance Deployment
The tier 4 requirement for Sloan's "Gunslingers" theme is:
       Includes at least two heavy warjacks in Kara's battlegroup.

  Do we think it would be beneficial to have an entry group that shows "battlegroup allocation" for list-building in general (outside of themes)?  It seems like a lot of work from the catalog side, ensuring that "marhalled" or "junior warcaster" options are only available if the corresponding solo/unit is selected.  But it would technically make the list more correct.  Although to make it truly correct, we'd need entries for each specific marshal, which just seems like a bit of a maintenance headache.

**Comment by Obiken** [comment]
Not sure how I'd attack this, so far I've dismissed it as being too much hassle for little gain. But if we do want to support theme forces we need to find a way.
