### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Claspingrain** [BSData/warmahordes#50]
Would like to work on Circle orboros and the creation of the Grymkin faction on battlescribe.

**Comment by amis92** [comment]
Hello, @USERNAME. Please accept the invitation in the email or on the https://github.com/BSData/warmahordes/invitations. Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Cheers!
